//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class douong
    {
        public string Tendouong { get; set; }
        public string Madouong { get; set; }
        public Nullable<double> dongiaban { get; set; }
        public string Anh { get; set; }
        public Nullable<double> Dongianhap { get; set; }
        public string Mota { get; set; }
        public string Trongluong { get; set; }
        public string Maloai { get; set; }
    }
}
