//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBCAPHE8Entities : DbContext
    {
        public WEBCAPHE8Entities()
            : base("name=WEBCAPHE8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calamviec> Calamviecs { get; set; }
        public virtual DbSet<Chitietcalam> Chitietcalams { get; set; }
        public virtual DbSet<douong> douongs { get; set; }
        public virtual DbSet<Hoadonban> Hoadonbans { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<Loaidouong> Loaidouongs { get; set; }
        public virtual DbSet<Nhacungcap> Nhacungcaps { get; set; }
        public virtual DbSet<Nhanvien> Nhanviens { get; set; }
        public virtual DbSet<User_khach> User_khach { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ChitietHDB> ChitietHDBs { get; set; }
        public virtual DbSet<ChiTietHDN> ChiTietHDNs { get; set; }
    }
}
