//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public string TenNV { get; set; }
        public string MaNV { get; set; }
        public string GT { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Diachi { get; set; }
    }
}
