//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDN
    {
        public Nullable<int> SLNhap { get; set; }
        public string Madouong { get; set; }
        public string SoHDN { get; set; }
    }
}
