//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonban
    {
        public string SoHDB { get; set; }
        public Nullable<System.DateTime> Ngayban { get; set; }
        public string MaNV { get; set; }
        public string MaKH { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
    }
}
