//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public Nullable<int> soDienThoai { get; set; }
        public string email { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> access { get; set; }
        public string img { get; set; }
    }
}
